# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dog_shelter_admin_change_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminChangeWindow(object):
    def setupUi(self, AdminChangeWindow):
        AdminChangeWindow.setObjectName("AdminChangeWindow")
        AdminChangeWindow.resize(544, 154)
        AdminChangeWindow.setStyleSheet("background-color: rgb(232, 232, 174)")
        self.centralwidget = QtWidgets.QWidget(AdminChangeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_add_dog = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_dog.setGeometry(QtCore.QRect(40, 30, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_add_dog.setFont(font)
        self.btn_add_dog.setObjectName("btn_add_dog")
        self.btn_add_breed = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_breed.setGeometry(QtCore.QRect(290, 30, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_add_breed.setFont(font)
        self.btn_add_breed.setObjectName("btn_add_breed")
        AdminChangeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AdminChangeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 544, 26))
        self.menubar.setObjectName("menubar")
        AdminChangeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AdminChangeWindow)
        self.statusbar.setObjectName("statusbar")
        AdminChangeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AdminChangeWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminChangeWindow)

    def retranslateUi(self, AdminChangeWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminChangeWindow.setWindowTitle(_translate("AdminChangeWindow", "MainWindow"))
        self.btn_add_dog.setText(_translate("AdminChangeWindow", "Добавить собаку"))
        self.btn_add_breed.setText(_translate("AdminChangeWindow", "Добавить породу"))
